@server = http://localhost:4004

# @name createShipments batch
POST {{server}}/odata/v4/bulk-test/$batch
Content-Type: multipart/mixed; boundary=batch

--batch
Content-Type: multipart/mixed; boundary=changeset

--changeset
Content-Type: application/http
Content-Transfer-Encoding: binary

POST /odata/v4/bulk-test/StartEntity
Content-Type: application/json

{"ID":"1","name":"Shipment 1"}
--changeset
Content-Type: application/http
Content-Transfer-Encoding: binary

POST /odata/v4/bulk-test/StartEntity
Content-Type: application/json

{"ID":"2","name":"Shipment 2"}
--changeset
Content-Type: application/http
Content-Transfer-Encoding: binary

POST /odata/v4/bulk-test/StartEntity
Content-Type: application/json

{"ID":"3","name":"Shipment 3"}
--changeset
Content-Type: application/http
Content-Transfer-Encoding: binary

POST /odata/v4/bulk-test/StartEntity
Content-Type: application/json

{"ID":"4","name":"Shipment 4"}
--changeset
Content-Type: application/http
Content-Transfer-Encoding: binary

POST /odata/v4/bulk-test/StartEntity
Content-Type: application/json

{"ID":"5","name":"Shipment 5"}
--changeset--
--batch--
###