@server = http://localhost:4004

# @name createShipment with annotation
POST {{server}}/odata/v4/local-test/Test
Content-Type: application/json

{
    "ID": "12345",
    "name": "Test Name",
    "age": 21
}

###

# @name createShipment with annotation
DELETE {{server}}/odata/v4/local-test/Test('12345')

###