
@server = http://localhost:4004

# @name createShipment with annotation
POST {{server}}/odata/v4/test/AnnotatedShipments
Content-Type: application/json

{
    "ID": "123456",
    "address": "Germany",
    "date": "2026",
    "weight": 1000
}

###

# @name createShipment without annotation
POST {{server}}/odata/v4/test/UnAnnotatedShipments
Content-Type: application/json

{
    "ID": "12345",
    "address": "Germany",
    "date": "2026",
    "weight": 1
}

###


# @name updateShipment
PATCH {{server}}/odata/v4/test/AnnotatedShipments('1234')
Content-Type: application/json

{
    "weight": 1000
}

###

# @name deleteShipment
DELETE {{server}}/odata/v4/test/AnnotatedShipments('1234')