name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]
        cds-version: [latest]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g @sap/cds-dk@${{ matrix.cds-version }}
      - run: npm i
      - run: npm run build
      - run: cd tests/bookshop && npm run build
      - run: npm run test
  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
      - name: get-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
      - name: Parse changelog
        id: parse-changelog
        uses: schwma/parse-changelog-action@v1.0.0
        with:
          version: '${{ steps.package-version.outputs.current-version }}'
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ steps.package-version.outputs.current-version }}'
          body: '${{ steps.parse-changelog.outputs.body }}'
      - run: npm publish --access public --provenance
